### ISSUE TITLE
The program crashes

### ISSUE THREAD

**Issue by Quits123** [bassel27/Trading-Core#9]
I installed the code and the bot works it opens the website and logs in but then it reloads the website and closes the program without a error message

**Comment by bassel27** [comment]
Thank you for bringing this to my attention. I'm sorry to hear that you are experiencing issues with the program. I appreciate you taking the time to test it out and provide feedback.

Based on the information you provided, I have made some updates to the program to address the issue of the program reloading the website and closing without any error messages. However, I would like to inform you that the web scraping code for executing trades needs to be updated to match Investopedia's new UI. Now, the program opens and works properly until executing a trade.

I appreciate your patience and understanding as I work to improve the program. If you have any further issues or concerns, please don't hesitate to let me know.
